/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CampaignsCampaignIdSessionsIndexRouteImport } from './routes/campaigns/$campaignId/sessions/index'
import { Route as CampaignsCampaignIdSessionsSessionIdRouteImport } from './routes/campaigns/$campaignId/sessions/$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdSessionsIndexRoute =
  CampaignsCampaignIdSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdSessionsSessionIdRoute =
  CampaignsCampaignIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof CampaignsCampaignIdSessionsSessionIdRoute
  '/campaigns/$campaignId/sessions/': typeof CampaignsCampaignIdSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns': typeof CampaignsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof CampaignsCampaignIdSessionsSessionIdRoute
  '/campaigns/$campaignId/sessions': typeof CampaignsCampaignIdSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/login': typeof LoginRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof CampaignsCampaignIdSessionsSessionIdRoute
  '/campaigns/$campaignId/sessions/': typeof CampaignsCampaignIdSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/'
    | '/api/auth/$'
    | '/campaigns/$campaignId/sessions/$sessionId'
    | '/campaigns/$campaignId/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns'
    | '/api/auth/$'
    | '/campaigns/$campaignId/sessions/$sessionId'
    | '/campaigns/$campaignId/sessions'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/login'
    | '/campaigns/$campaignId'
    | '/campaigns/'
    | '/api/auth/$'
    | '/campaigns/$campaignId/sessions/$sessionId'
    | '/campaigns/$campaignId/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/sessions/': {
      id: '/campaigns/$campaignId/sessions/'
      path: '/sessions'
      fullPath: '/campaigns/$campaignId/sessions/'
      preLoaderRoute: typeof CampaignsCampaignIdSessionsIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/sessions/$sessionId': {
      id: '/campaigns/$campaignId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/campaigns/$campaignId/sessions/$sessionId'
      preLoaderRoute: typeof CampaignsCampaignIdSessionsSessionIdRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdSessionsSessionIdRoute: typeof CampaignsCampaignIdSessionsSessionIdRoute
  CampaignsCampaignIdSessionsIndexRoute: typeof CampaignsCampaignIdSessionsIndexRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdSessionsSessionIdRoute:
    CampaignsCampaignIdSessionsSessionIdRoute,
  CampaignsCampaignIdSessionsIndexRoute: CampaignsCampaignIdSessionsIndexRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
